apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus/rules/AlertManagerFailing.yml"
  - "prometheus/rules/NodeMemoryFull.yml"
  - "prometheus/rules/HostNetworkTooMuchData.yml"
  - "prometheus/rules/DiskAlmostFull.yml"
scrape_configs:
  - job_name: "project2_metrics"

      # metrics_path defaults to '/metrics'
      metrics_path: '/actuator/prometheus'
      # scheme defaults to 'http'.

      static_configs:
        - targets: [ "localhost:8085" ]
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000